config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update]
  resources :users, only: [:index,:show,:edit,:create,:destroy,:update]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,length:{maximum:200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :books, dependent: :destroy

has_one_attached :profile_image

validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
validates :introduction, length:{maximum:50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end




end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user =current_user
      @books = Book.all
      render :index
    end
  end


  def index
    @user = current_user
    @book = Book.new
    @books = Book.all

  end

  def show
    @user = current_user
    @book = Book.find(params[:id])
    @books = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
  def correct_user
  @book = Book.find(params[:id])
  @user = @book.user
  redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end

  def index
    @user = current_user
    @users =User.all
    @book = Book.new
  end

  def show
    @user =User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def create

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id),notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

    private
  def user_params
    params.require(:user).permit(:name,:introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    # @user = @user1.user
    redirect_to(user_path(current_user)) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div>
  <h2>Books</h2>
  <table>
    <thead>
      <th>Title</th>
      <th>Opinion</th>
    </thead>
      <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
      </tbody>
  </table>
</div>

app/views/books/_new.html.erb
 <h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<body>
  <main>

    <div div class="container">
      <div class="row">
        <h1>Editing Book</h1>
      </div>
      <%= form_with model:@book,local:true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :opinion %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit  %>
  </div>
    	<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path %>
<% end %>

    </div>
  </main>
</body>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/info', user: @user %>
      <%= render 'new', book: @book %>
      </div>
      <div class='col-md-8 offset-md-1'>
      <%= render 'list', books: @books %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
  <%= form_with model: @book do |f| %>
    <h4>本のタイトル</h4>
      <%= f.text_field :title %>
    <h4>感想</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<main>
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
      <%= render 'users/info', user: @book.user %>
      <%= render 'new', book: @books %>
      </div>
      <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table>
        <tbody>
          <tr>
            <td><%=link_to user_path(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %>
            <%= @book.user.name %>
            <% end %>
            </td>
              <td><%= link_to @book.title, @book %></td>
              <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success edit_book_path" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger destroy_book_path" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<html>
  <body>
    <h1>
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </h1>
  </body>
</html>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to <i class="fas fa-book"></i><storong>Bookers</strong>!!
        </h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-1o mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/5529daca03.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
  <main>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </main>
  <footer>
    <div class="container mt-5">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </footer>

  </body>
</html>

app/views/users/_info.html.erb
<div>
  <h2>User info</h2>

  <%= image_tag user.get_profile_image, size:"50x50" %>
  <table>
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    <tbody>
  </table>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image, size:"50x50" %>
        <table>
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          <tbody>
        </table>
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
        <%= render 'books/new', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
      <table>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image, size:"50x50" %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
    <%= image_tag @user.get_profile_image, size:"50x50" %>
    <table>
      <tbody>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      <tbody>
    </table>
    <%= link_to  edit_user_path,class: 'btn-outline-secondary btn-block edit_user_path' do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
    <%= render 'books/new', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
  <%= render 'books/list', books: @books %>
  </div>
</div>
</main>